# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
